# Módulo 4 · Tarea 4 — NumPy y pandas para análisis de datos

## 1. Trabajando con NumPy

In [37]:
#Import de la libreria.

import numpy as np

#Array del 10 al 100 incluyendo estos dos.

array = np.arange(10,101)
print(array)

#Array del 10 al 100 al reves.

print(np.flip(array))

#Array con valores del 0 al 8 en 2d (3x3).

array_2d_3x3 = np.arange(9).reshape(3, 3)
print(array_2d_3x3)

#Array identidad en 2d (6x6).

array_identidad = np.eye(6)
print(array_identidad)

#Array con valores random en 3d (3x3x3).

array_3d_random = np.random.random((3,3,3))
print(array_3d_random)

#Array randoms y comparacion.

arrayA = np.random.random(5)
arrayB = np.random.random(5)
comparacion = np.array_equal(arrayA, arrayB)
if comparacion:
    print("Los Arrays son iguales")
else:
    print("Los Arrays no son iguales")


[ 10  11  12  13  14  15  16  17  18  19  20  21  22  23  24  25  26  27
  28  29  30  31  32  33  34  35  36  37  38  39  40  41  42  43  44  45
  46  47  48  49  50  51  52  53  54  55  56  57  58  59  60  61  62  63
  64  65  66  67  68  69  70  71  72  73  74  75  76  77  78  79  80  81
  82  83  84  85  86  87  88  89  90  91  92  93  94  95  96  97  98  99
 100]
[100  99  98  97  96  95  94  93  92  91  90  89  88  87  86  85  84  83
  82  81  80  79  78  77  76  75  74  73  72  71  70  69  68  67  66  65
  64  63  62  61  60  59  58  57  56  55  54  53  52  51  50  49  48  47
  46  45  44  43  42  41  40  39  38  37  36  35  34  33  32  31  30  29
  28  27  26  25  24  23  22  21  20  19  18  17  16  15  14  13  12  11
  10]
[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]
[[[0.97756094 0.17346312 0.54120225]
  [0.17393353 0.18341291 0.88281405]
  [0.0750358  0.01826024 0.80

## 2. NumPy: conversión de valores

In [ ]:
#Import de la libreria.

import numpy as np

#Array de dolares del 1 al 1000 con 100 valores.

dolares = np.random.randint(1, 1001, 100)

#Conversion de dolares a euros y redondeo.

euros = np.round(dolares * 0.874413, 2)

#Prints de los dos arrays.

print(dolares)
print(euros)

[508 389 928 982 949 414 625 116 136 578 307 604 958 746 396 349 606 226
 827 866 317 185 437 832 666  37 667 826 274  50 950 414 370 245  11 482
 459 899  44  28 831 197 346 503 117 571 831 514 536 396 206 736 611 380
 609 242 660 605 133 907 132 290 159 571 538 811 770 759 243 866 538 555
 757 468 423 112 664 854 617 171 308 340 260 469 620 949 389 704 267 524
 645 365 106  12 390 572 353 869 662 364]
[444.2  340.15 811.46 858.67 829.82 362.01 546.51 101.43 118.92 505.41
 268.44 528.15 837.69 652.31 346.27 305.17 529.89 197.62 723.14 757.24
 277.19 161.77 382.12 727.51 582.36  32.35 583.23 722.27 239.59  43.72
 830.69 362.01 323.53 214.23   9.62 421.47 401.36 786.1   38.47  24.48
 726.64 172.26 302.55 439.83 102.31 499.29 726.64 449.45 468.69 346.27
 180.13 643.57 534.27 332.28 532.52 211.61 577.11 529.02 116.3  793.09
 115.42 253.58 139.03 499.29 470.43 709.15 673.3  663.68 212.48 757.24
 470.43 485.3  661.93 409.23 369.88  97.93 580.61 746.75 539.51 149.52
 269.32 297.3  227.35 410

## 3. pandas y dataset tips de seaborn

In [ ]:
#Import de todas las librerias usadas.

import pandas as pd
import seaborn as sns

#Declaracion de la variable df.

df = sns.load_dataset("tips")

#Muestra los 5 primeros registros.

display(df.head(5))

#Descripción de los atributos del dataset:

print("total_bill: importe total de la cuenta (USD).\ntip: propina (USD).\nsex: sexo de la persona que pagó.\nsmoker: si había fumadores en la mesa.\nday: día de la semana.\ntime: momento del día.\nsize: número de personas en la mesa.")

#Muestra el número total de registros.

print(len(df))

#Calcula la propina media y la cuenta media.

print(f"La media de la propina es de: {df["tip"].median().round(2)} y la media de la cuenta es de: {df["total_bill"].median().round(2)}")

#Crea la columna pct_tip y muestra las 5 filas con mayor porcentaje.

df["pct_tip"] = ((df["tip"] / df["total_bill"]) * 100).round(2)
print(df.sort_values("pct_tip", ascending = False).head(5))

#Muestra las 10 cuentas más altas con su propina y porcentaje.

print(df.sort_values("total_bill", ascending = False).head(10)[["total_bill", "tip", "pct_tip"]])

#Muestra el promedio de propina por día ordenado de mayor a menor.

print(df.groupby("day")["tip"].mean().round(2))

#Muestra el promedio de pct_tip por sexo y por condición de fumador.

print(df.groupby(["smoker", "sex"])["pct_tip"].mean().round(2))

#Indica el día y momento en el que se registró la cuenta más alta.

print(df.loc[df["total_bill"].idxmax()][["total_bill", "day", "time"]])

#Muestra cuántos registros corresponden a Lunch y Dinner.

print(df["time"].value_counts())

#Muestra la propina media por tamaño de mesa e indica cuál deja mayor porcentaje.

print(df.groupby("size")["pct_tip"].mean().round(2))

#Filtra mesas de 5 o más personas y calcula su pct_tip medio.

print(df[df["size"] >= 5]["pct_tip"].mean().round(2))

#Calcula, por día, la facturación total y el total de propinas.

print(df.groupby("day")[["total_bill", "tip"]].sum().round(2))

#Calcula la correlación entre total_bill y tip y comenta el resultado.

print(df["total_bill"].corr(df["tip"]).round(2))

#Exporta a CSV las columnas indicadas en un archivo tips_resumen.csv.

df[["total_bill", "tip", "pct_tip", "day", "time", "size"]].to_csv("tips_resumen.csv", index=False)


,total_bill,tip,sex,smoker,day,time,size
0,16.99,1.01,Female,No,Sun,Dinner,2
1,10.34,1.66,Male,No,Sun,Dinner,3
2,21.01,3.50,Male,No,Sun,Dinner,3
3,23.68,3.31,Male,No,Sun,Dinner,2
4,24.59,3.61,Female,No,Sun,Dinner,4


total_bill: importe total de la cuenta (USD).
tip: propina (USD).
sex: sexo de la persona que pagó.
smoker: si había fumadores en la mesa.
day: día de la semana.
time: momento del día.
size: número de personas en la mesa.
244
La media de la propina es de: 2.9 y la media de la cuenta es de: 17.8
     total_bill   tip     sex smoker  day    time  size  pct_tip
172        7.25  5.15    Male    Yes  Sun  Dinner     2    71.03
178        9.60  4.00  Female    Yes  Sun  Dinner     2    41.67
67         3.07  1.00  Female    Yes  Sat  Dinner     1    32.57
232       11.61  3.39    Male     No  Sat  Dinner     2    29.20
183       23.17  6.50    Male    Yes  Sun  Dinner     4    28.05
     total_bill    tip  pct_tip
170       50.81  10.00    19.68
212       48.33   9.00    18.62
59        48.27   6.73    13.94
156       48.17   5.00    10.38
182       45.35   3.50     7.72
102       44.30   2.50     5.64
197       43.11   5.00    11.60
142       41.19   5.00    12.14
184       40.55   3.00    

## 4. pandas y datasets de IMDb